# Options: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "quarterly"
    target-branch: "develop"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "quarterly"
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    target-branch: "develop"
