ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.16"
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi, jupyter, pyproject ]
        args: [ "--fix", "--show-fixes" ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v2.1.0"
    hooks:
      - id: mypy
        files: "^src/airsenal/"
        additional_dependencies:
          - pytest
          - types-dateparser
          - types-requests
          - types-python-dateutil
