"""
map between different conventions used in different data sources.
"""

positions = {1: "GK", 2: "DEF", 3: "MID", 4: "FWD", 5: "MNG"}

alternative_team_names = {
    "ARS": ["1", "Arsenal", "Arsenal FC"],
    "AVL": ["2", "Aston Villa", "Aston Villa FC"],
    "BOU": ["3", "Bournemouth", "AFC Bournemouth"],
    "BRE": ["4", "Brentford", "Brentford FC"],
    "BHA": [
        "5",
        "Brighton and Hove Albion",
        "Brighton",
        "Brighton & Hove Albion FC",
        "Brighton & Hove Albion",
    ],
    "BUR": ["6", "Burnley", "Burnley FC"],
    "CHE": ["7", "Chelsea", "Chelsea FC"],
    "CRY": ["8", "Crystal Palace", "Crystal Palace FC"],
    "EVE": ["9", "Everton", "Everton FC"],
    "FUL": ["10", "Fulham", "Fulham FC"],
    "LEE": ["11", "Leeds", "Leeds United", "Leeds Utd"],
    "LIV": ["12", "Liverpool", "Liverpool FC"],
    "MCI": ["13", "Manchester City", "Man City", "Manchester City FC"],
    "MUN": [
        "14",
        "Manchester United",
        "Man Utd",
        "Manchester United FC",
        "Manchester Utd",
    ],
    "NEW": [
        "15",
        "Newcastle United",
        "Newcastle",
        "Newcastle United FC",
        "Newcastle Utd",
    ],
    "NFO": ["16", "Nott'm Forest", "Nottingham Forest"],
    "TOT": ["17", "Tottenham Hotspur", "Spurs", "Tottenham Hotspur FC"],
    "SUN": ["18", "Sunderland"],
    "WHU": ["19", "West Ham United", "West Ham", "West Ham United FC"],
    "WOL": ["20", "Wolves", "Wolverhampton Wanderers", "Wolverhampton Wanderers FC"],
    "LUT": ["Luton", "Luton Town"],
    "SHU": ["Sheffield United", "Sheffield Utd"],
    "NOR": ["Norwich City", "Norwich"],
    "WAT": ["Watford", "Watford FC"],
    "WBA": ["West Bromwich Albion", "West Brom"],
    "SWA": ["Swansea City"],
    "STK": ["Stoke City", "Stoke"],
    "MID": ["Middlesbrough"],
    "HUL": ["Hull", "Hull City"],
    "QPR": ["Queens Park Rangers"],
    "CAR": ["Cardiff", "Cardiff City", "Cardiff City FC"],
    "HUD": ["Huddersfield Town", "Huddersfield", "Huddersfield Town AFC"],
    "DER": ["Derby", "Derby County"],
    "IPS": ["Ipswich", "Ipswich Town"],
    "LEI": ["Leicester", "Leicester City", "Leicester City FC"],
    "SOU": ["Southampton", "Southampton FC"],
}
