"""
Tests for the MCTS-based multi-week transfer search
(airsenal.framework.mcts_optimization).
"""

from types import SimpleNamespace
from unittest.mock import patch

from airsenal.framework.mcts_optimization import extract_best_trajectory, run_mcts_tree
from airsenal.framework.optimization_utils import next_week_transfers

TAG = "DUMMY"
SEASON = "2526"


def _make_best_transfers_side_effect(points_by_action):
    """A make_best_transfers double returning a fixed score per num_transfers value,
    ignoring everything else about the squad/gameweeks - lets us construct scenarios
    with a clearly-best action to check the search actually prefers it.
    """

    def side_effect(
        num_transfers,
        squad,
        tag,
        gameweeks,
        root_gw,
        season,
        num_iter,
        update_func_and_args,
    ):
        new_squad = SimpleNamespace(budget=0)
        transfer_dict: dict[str, list] = {"in": [], "out": []}
        points = points_by_action.get(num_transfers, 0.0)
        return new_squad, transfer_dict, points

    return side_effect


def _run_search(gameweek_range, points_by_action, n_iterations, random_state):
    starting_squad = SimpleNamespace(budget=0)
    with (
        patch(
            "airsenal.framework.mcts_optimization.make_best_transfers",
            side_effect=_make_best_transfers_side_effect(points_by_action),
        ),
        patch(
            "airsenal.framework.mcts_optimization.get_discounted_squad_score",
            return_value=0.0,
        ),
    ):
        return run_mcts_tree(
            starting_squad,  # type: ignore[arg-type]
            gameweek_range,
            TAG,
            SEASON,
            chips_gw_dict={},
            num_free_transfers=2,
            n_iterations=n_iterations,
            max_free_transfers=2,
            random_state=random_state,
        )


def test_ucb1_prefers_higher_value_branch():
    """
    Over enough iterations, the search should visit the genuinely-best first-week
    action (num_transfers=1, scoring far higher than 0 or 2 every time) more than
    the others - the whole point of UCB1-guided selection over blind/uniform
    exploration.
    """
    root = _run_search(
        gameweek_range=[1, 2],
        points_by_action={0: 1.0, 1: 20.0, 2: 1.0},
        n_iterations=300,
        random_state=42,
    )

    assert root.children, "search should have expanded at least one action"
    most_visited = max(root.children.values(), key=lambda c: c.visits)
    assert most_visited.action[0] == 1


def test_actions_never_fall_outside_next_week_transfers():
    """
    MCTS's action space is generated by next_week_transfers() (already covered by
    its own tests) - confirm every action actually tried during the search is one
    it would have offered, for both the root and a deeper node.
    """
    root = _run_search(
        gameweek_range=[1, 2],
        points_by_action={0: 1.0, 1: 2.0, 2: 1.5},
        n_iterations=100,
        random_state=7,
    )

    valid_root_actions = set(
        next_week_transfers(
            (root.free_transfers, root.hit_so_far, root.strat_dict),
            1,
            max_opt_transfers=2,
            max_free_transfers=2,
            chips={},
        )
    )
    assert set(root.children.keys()) <= valid_root_actions

    for child in root.children.values():
        if not child.children:
            continue
        valid_child_actions = set(
            next_week_transfers(
                (child.free_transfers, child.hit_so_far, child.strat_dict),
                2,
                max_opt_transfers=2,
                max_free_transfers=2,
                chips={},
            )
        )
        assert set(child.children.keys()) <= valid_child_actions


def test_extract_best_trajectory_produces_complete_strategy():
    """
    The extracted strategy should cover every gameweek in the horizon (even if the
    search didn't fully expand the winning path all the way to the end - see
    extract_best_trajectory's fallback), with the string-keyed-by-gameweek shape
    fill_suggestion_table/fill_transaction_table/print_strat expect.
    """
    gameweek_range = [1, 2, 3]
    root = _run_search(
        gameweek_range=gameweek_range,
        points_by_action={0: 1.0, 1: 2.0, 2: 1.5},
        n_iterations=100,
        random_state=1,
    )

    with (
        patch(
            "airsenal.framework.mcts_optimization.make_best_transfers",
            side_effect=_make_best_transfers_side_effect({0: 1.0, 1: 2.0, 2: 1.5}),
        ),
        patch(
            "airsenal.framework.mcts_optimization.get_discounted_squad_score",
            return_value=0.0,
        ),
    ):
        strategy = extract_best_trajectory(
            root,
            TAG,
            SEASON,
            chips_gw_dict={},
            max_total_hit=None,
            allow_unused_transfers=False,
            max_free_transfers=2,
            num_iterations=10,
        )

    expected_gws = {str(gw) for gw in gameweek_range}
    assert set(strategy["points_per_gw"].keys()) == expected_gws
    assert set(strategy["players_in"].keys()) == expected_gws
    assert set(strategy["players_out"].keys()) == expected_gws
    assert set(strategy["chips_played"].keys()) == expected_gws
    assert set(strategy["num_transfers"].keys()) == expected_gws
    assert "total_score" in strategy
    assert "_gameweek_range" not in strategy
